### PR TITLE
Async errors caught in domain

### PR DESCRIPTION
**Pull request by taylorhakes**
I am using this library in the browser, but noticed it doesn't catch async errors. I saw pull request #5 that attempts to do that? I don't think that is the right approach though because that will catch all errors, not just errors in the domain.

This pull request wraps setTimeout, setInterval, setImmediate and adds tests that failed in the previous code. @balupton is this something you would consider merging or does this belong in a fork?

### CODE REVIEW

**Comment by balupton** [comment]
Thanks for this. Seems nifty. A few points:

> This pull request wraps setTimeout, setInterval, setImmediate

How does this actually work to accomplish the aims? I can see what the code does,  but unsure why such code changes accomplish the result.

How safe is this?

Is this how domains work inside node.js as well? Or could we risk providing an emulated behaviour for this that could cause unexpected results?

**Comment by taylorhakes** [comment]
> How does this actually work

Essentially this overrides setTimeout, setInterval, etc in the following way.
```js
setTimeout = function newSetTimeout(fn, time) {
  return originalSetTimeout(function() {
    try {
      fn();
    } catch (e) {
      emitError(e);
    }
  }, time);
};
```
It does this recursively so setTimeout calls inside the above setTimeout are also caught.

> How safe is this?

I am pretty confident about it for common libraries. I can't say for certain there won't be some weird library that this causes issues.  It only replaces `setTimeout`, etc while the function is running though. That is the `wrapAsyncFns` and `unwrapAsyncFns` part. The async functions still behave like the original functions, but just have a try/catch at the top level.


> Is this how domains work inside node.js as well? 

Are you taking about the behavior or implementation?
- Behavior: Yes, domains catch all async errors for timers created inside the domain
- Implementation: I am not sure how Node does this internally.

I am submitting this pull request because browser domains do not behave like Node domains. This was an issue for me when using browserify. Maybe @substack  has an opinion on these changes?

**Comment by balupton** [comment]
Took a look into how it works in Node:

- Original implementation and details: https://github.com/nodejs/node/commit/963459d736d6594de641aff4d8767da113359457

- Current implementation in 5.6.0: https://github.com/nodejs/node/blob/v5.6.0/lib/domain.js

Seems the idea is to extend EventEmitter or listen to `process.on('uncaughtException')` which we could do properly using the [browser's `window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror)

However, seems they have identified better ways of doing this:

- https://github.com/nodejs/node/issues/66#issuecomment-179478091

**Comment by taylorhakes** [comment]
If you look at nodejs/node@963459d. It requires changes to the internals of timers which essentially I am doing with my try/catch solution. 

I agree that a `domain.enter`/`domain.exit `is probably the ideal method, so you can solve those functions not being a noop.

Are you suggesting not using try/catch at all (even for sync) and just use `window.onerror`? That might be possible, but it will still need to wrap timer functions. You will probably also need to put some variables  on the window scope.

A `window.onerror` solution also has a downside of not actually catching errors. It will always call the other window.onerror handlers.

**Comment by balupton** [comment]
I'm thinking this will need to be under a special flag or something. Or its own dependency that people can then swap into with a browserify config option. As the risks for breaking things is there, even if it is small. So pushing this on the millions of month users could become a problem - as if this is default, and not opt out, it could introduce some very hard to debug problems for people, when they were not expecting it.

Will close for now, but this should happen, in one way or another. It is a good initiative.

**Pull request closed without merging**
